# <center>Ma trận trong Python</center>

## Mục lục
* [Thực hành](#c1)
    * [Khai báo ma trận](#c11)
    * [Các phép toán cơ bản trên ma trận](#c12)
    * [Định thức](#c13)
    * [Nghịch đảo ma trận](#c14)
* [Đồ án 1](#c2)
    * [Nội dung đồ án](#c21)
    * [Quy định nộp bài](#c22)
    * [Quy định chấm bài](#c23)

## Thực hành <a class="anchor" id="c1"></a>

Trong bài lab này, chúng ta sẽ đồng thời sử dụng `list` và  `NumPy` để thực hiện các phép toán trên ma trận.

Trong đó, sử dụng `list` để thực hiện các phép toán bằng code thủ công; sử dụng `NumPy` để gọi các hàm có sẵn trong thư viện.

In [1]:
import numpy as np

def my_print(x, sep=" "):
    if isinstance(x, list) and x:
        if isinstance(x[0], list): # list of list
            m, n = len(x), len(x[0])
            widths = [max(len(str(ai[j])) for ai in x) for j in range(n)]
            rows = [sep.join(format(str(ai[j]), f">{widths[j]}") for j in range(n)) for ai in x]
            print("[" + "\n".join((" [" if i > 0 else "[") + rows[i] + "]" for i in range(m)) + "]")
        else: # list
            print("[" + sep.join(str(e) for e in x) + "]")
    else:
        print(x)

### Khai báo ma trận <a class="anchor" id="c11"></a>

Trong Python, ma trận có thể biểu diễn bằng kiểu dữ liệu `list` (`list` of `list`) hoặc mảng NumPy 2 chiều (`np.array`). Giả sử với ma trận:
$$A = \begin{bmatrix}
    1   & 1.5 & -1.2\\ 
    2   & 3.7 & 8\\ 
    3.5 & 2.5 & 4
    \end{bmatrix}$$

Ta có thể biểu diễn bằng kiểu dữ liệu `list` như sau:

In [2]:
A_list = [[1, 1.5, -1.2],
          [2, 3.7, 8],
          [3.5, 2.5, 4]]

print(f'- The number of rows: {len(A_list)}\n- The number of columns: {len(A_list[0])}')
my_print(A_list)

- The number of rows: 3
- The number of columns: 3
[[  1 1.5 -1.2]
 [  2 3.7    8]
 [3.5 2.5    4]]


Và có thể biểu diễn trong NumPy như sau:

In [3]:
A_np = np.array(A_list)

print(f'- The number of rows: {A_np.shape[0]}\n- The number of cols: {A_np.shape[1]}')
print(A_np)

- The number of rows: 3
- The number of cols: 3
[[ 1.   1.5 -1.2]
 [ 2.   3.7  8. ]
 [ 3.5  2.5  4. ]]


#### Khởi tạo ma trận toàn 0

##### Trên `list` 

In [4]:
def create_zero_matrix(n_row, n_col):
    return [[0 for _ in range(n_col)] for _ in range(n_row)]

In [5]:
my_print(create_zero_matrix(3, 3))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


##### Trên `NumPy`

In [6]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Khai báo ma trận toàn 1

In [ ]:
### YOUR CODE HERE

#### Khai báo ma trận đơn vị

##### Trên `list`

In [7]:
def create_identity_matrix(n):
    return [[1 if i == j else 0 for j in range(n)] for i in range(n)]

In [8]:
my_print(create_identity_matrix(3))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


##### Trên `NumPy`

In [9]:
my_print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Các phép toán cơ bản trên ma trận <a class="anchor" id="c12"></a>

#### Nhân số với ma trận

In [10]:
def multiply_scalar_matrix(scalar, A_list):
    return [[scalar * a for a in a_row] for a_row in A_list]

In [11]:
my_print(multiply_scalar_matrix(2, A_list))

[[  2 3.0 -2.4]
 [  4 7.4   16]
 [7.0 5.0    8]]


#### Cộng ma trận

##### Cộng ma trận với ma trận

###### Thực hiện trên `A_list` (cách làm thủ công)

In [14]:
def add_matrix_list(A_list, B_list):
#     # Cách 1: Cơ bản
#     # Khởi tạo ma trận kết quả
#     C_list = [[0 for _ in range(len(A_list[0]))] for _ in range(len(A_list))]

#     m_row = len(A_list)
#     n_col = len(A_list[0])
#     for i_row in range(m_row):
#         for i_col in range(n_col):
#             C_list[i_row][i_col] = A_list[i_row][i_col] + B_list[i_row][i_col]
     
    
    # Cách 2: List Comprehension
    C_list = [[a + b for (a, b) in zip(a_row, b_row)] for (a_row, b_row) in zip(A_list, B_list)]   
    
    return C_list

In [15]:
# Tạo ra ma trận cần cộng
B_list = [[2, 1.5, 1.2],
          [3, 7, -9.5],
          [5.5, 2, 4]]

my_print(A_list)
print()
my_print(B_list)
print()

my_print(add_matrix_list(A_list, B_list))

[[  1 1.5 -1.2]
 [  2 3.7    8]
 [3.5 2.5    4]]

[[  2 1.5  1.2]
 [  3   7 -9.5]
 [5.5   2    4]]

[[  3  3.0  0.0]
 [  5 10.7 -1.5]
 [9.0  4.5    8]]


###### Thực hiện trên `A_np` (sử dụng hàm của thư viện `NumPy`)

In [16]:
B_np = np.array(B_list)

print(A_np + B_np)

[[ 3.   3.   0. ]
 [ 5.  10.7 -1.5]
 [ 9.   4.5  8. ]]


##### Cộng ma trận với 1 số

In [ ]:
### YOUR CODE HERE

#### Trừ, nhân, chia các phần tử tương ứng của 2 ma trận

Tương tự với cộng 2 ma trận, các phép toán còn lại tương tự.

##### Trên `A_list`

In [18]:
def op_matrix_list(A_list, B_list, op):
    if op == '+':
        return [[a + b for (a, b) in zip(a_row, b_row)] for (a_row, b_row) in zip(A_list, B_list)]
    elif op == '-':
        return [[a - b for (a, b) in zip(a_row, b_row)] for (a_row, b_row) in zip(A_list, B_list)]
    elif op == '*': # element-wise
        return [[a * b for (a, b) in zip(a_row, b_row)] for (a_row, b_row) in zip(A_list, B_list)]
    elif op == '/': # element-wise
        return [[a / b for (a, b) in zip(a_row, b_row)] for (a_row, b_row) in zip(A_list, B_list)]
    else:
        raise ValueError(f'Can\'t understand operator {op}')

In [19]:
print('Subtraction of Matrices:')
my_print(op_matrix_list(A_list, B_list, '-'))

print('\nElement-Wise Multiplication of Matrices:')
my_print(op_matrix_list(A_list, B_list, '*'))

print('\nElement-Wise Division of Matrices:') 
my_print(op_matrix_list(A_list, B_list, '/'))

Subtraction of Matrices:
[[  -1  0.0 -2.4]
 [  -1 -3.3 17.5]
 [-2.0  0.5    0]]

Element-Wise Multiplication of Matrices:
[[    2               2.25 -1.44]
 [    6 25.900000000000002 -76.0]
 [19.25                5.0    16]]

Element-Wise Division of Matrices:
[[               0.5                1.0                -1.0]
 [0.6666666666666666 0.5285714285714286 -0.8421052631578947]
 [0.6363636363636364               1.25                 1.0]]


##### Trên `A_np`

In [20]:
print('Subtraction of Matrices: \n', A_np - B_np)
print('\nElement-Wise Multiplication of Matrices: \n', A_np * B_np)
print('\nElement-Wise Division of Matrices: \n', A_np / B_np)

Subtraction of Matrices: 
 [[-1.   0.  -2.4]
 [-1.  -3.3 17.5]
 [-2.   0.5  0. ]]

Element-Wise Multiplication of Matrices: 
 [[  2.     2.25  -1.44]
 [  6.    25.9  -76.  ]
 [ 19.25   5.    16.  ]]

Element-Wise Division of Matrices: 
 [[ 0.5         1.         -1.        ]
 [ 0.66666667  0.52857143 -0.84210526]
 [ 0.63636364  1.25        1.        ]]


#### Nhân 2 ma trận

##### Trên `A_list`

In [21]:
def multiply_matrix(A_list, B_list):
    m_row = len(A_list)
    n_col = len(B_list[0])
    
    # Khởi tạo ma trận kết quả
    C_list = [[0 for _ in range(n_col)] for _ in range(m_row)]

    for i_row in range(m_row):
        for i_col in range(n_col):
            total = 0
            for i,a in enumerate(A_list[i_row]):  # Duyệt qua từng phần tử trong dòng thứ i_row (A_list)
                total += a*B_list[i][i_col]       # Nhân từng phần tử với phân tử thứ i trong cột thứ i_col (B_list)
            C_list[i_row][i_col] = total

    return C_list

In [23]:
multiply_matrix(A_list, B_list)

[[-0.09999999999999964, 9.6, -17.85],
 [59.1, 44.900000000000006, -0.75],
 [36.5, 30.75, -3.5500000000000007]]

##### Trên `A_np`

In [24]:
A_np @ B_np # np.matmul(A_np, B_np)

array([[ -0.1 ,   9.6 , -17.85],
       [ 59.1 ,  44.9 ,  -0.75],
       [ 36.5 ,  30.75,  -3.55]])

#### Chuyển vị ma trận

In [ ]:
### YOUR CODE HERE

### Định thức <a class="anchor" id="c13"></a>

In [25]:
A_list = [[0, 1, 2],
          [3, 5, 5],
          [5, 7, 5]]

A_np = np.array(A_list)

#### Trên `A_list`

In [26]:
def create_submatrix(A, i_row, i_col):
    sub_A = A[:] # Tạo ra ma trận mới giống A (clone A)
    
    # Bỏ dòng
    sub_A = sub_A[:i_row] + sub_A[i_row+1:]
    
    # Bỏ cột
    n_row_sub = len(sub_A)
    for i in range(n_row_sub): 
        sub_A[i] = sub_A[i][:i_col] + sub_A[i][i_col+1:]
        
    return sub_A


# Dành cho ma trận vuông
def calc_determinant(A):
    # Trường hợp cơ bản, định thức của ma trận 1x1
    if len(A) == 1 and len(A[0]) == 1:
        return A[0][0]
    
    total = 0
 
    # Duyệt qua từng cột để loại bỏ
    for i_col in range(len(A[0])):
        sub_A = create_submatrix(A, 0, i_col)
 
        # Tìm dấu
        sign = (-1) ** (i_col % 2)
        
        # Gọi đệ quy cho các ma trận con
        sub_det = calc_determinant(sub_A)
        
        # Cộng dồn định thức khi bỏ cột i_col
        total += sign * A[0][i_col] * sub_det 
 
    return total

In [27]:
calc_determinant(A_list)

2

#### Trên `A_np` 

In [28]:
np.linalg.det(A_np)

2.0000000000000036

### Nghịch đảo ma trận <a class="anchor" id="c14"></a>

#### Trên `A_list` 

In [29]:
def transpose(A):
    return list(map(list, zip(*A)))

# Cho ma trận vuông
def invert_matrix(A):
    n_row = len(A)
    n_col = len(A[0])
    
    # Nếu ma trận không vuông
    if n_row != n_col:
        raise ValueError('Not a square matrix')
        return None
    
    # Tính định thức cho ma trận
    det_A = calc_determinant(A)
    
    # Trả về None khi ma trận không khả nghịch
    if det_A == 0:
        raise ValueError('Matrix irreversible')
        return None
    
    # Xử lý trường hợp ma trận cấp 1
    if n_row == 1 and n_col == 1:
        return 1/det_A
    
    # Tạo ma trận kết quả
    A_res = [[0 for _ in range(n_col)] for _ in range(n_row)]
    
    # A_res = adj(A)/det_A -----------------------------------------------------------------
    # B1: Chuyển vị ma trận gốc
    A_trans = transpose(A)
    
    # B2: Tính adj(A) đồng thời gán kết quả vào A_res
    for i_row in range(n_row):
        for i_col in range(n_col):
            # Tạo ra các ma trận con
            sub_A = create_submatrix(A_trans, i_row, i_col)
 
            # Tìm dấu
            sign = (-1) ** (i_row + i_col)
            
            A_res[i_row][i_col] = sign * calc_determinant(sub_A)
 
    # B3: Chia định thức
    A_res = multiply_scalar_matrix(1/det_A, A_res)
    
    return A_res

In [30]:
my_print(invert_matrix(A_list))

[[-5.0  4.5 -2.5]
 [ 5.0 -5.0  3.0]
 [-2.0  2.5 -1.5]]


#### Trên `A_np` 

In [31]:
print(np.linalg.inv(A_np))

[[-5.   4.5 -2.5]
 [ 5.  -5.   3. ]
 [-2.   2.5 -1.5]]


Sau phần thực hành này, hy vọng các bạn sẽ thấy được sự hữu ích khi tận dụng các thư viện của Python ;-)

---

## Đồ án 1 <a class="anchor" id="c2"></a>

### Nội dung đồ án <a class="anchor" id="c21"></a>

#### Giới thiệu

Trong phần thực hiện, bạn đã được hướng dẫn cài đặt hàm tính định thức của ma trận vuông với phương pháp sử dụng phần bù đại số. Ngoài phương pháp phần bù đại số còn có một số phương pháp khác được sử dụng:
- [Sử dụng công thức Leibniz](https://en.wikipedia.org/wiki/Leibniz_formula_for_determinants)
- Sử dụng các phép biến đổi sơ cấp trên dòng
- ...

Tương tự, ngoài phương pháp sử dụng định thức con và phần bù đại số như đươc hướng dẫn, để tìm nghịch đảo cho ma trận vuông ta cũng có thể sử dụng các phép biến đổi sơ cấp trên dòng (phương pháp Gauss-Jordan).

#### Yêu cầu

Trong đồ án này, bạn được yêu cầu thực hiện các yêu cầu sau:

1. **Tìm hiểu** và **viết báo cáo** về phương pháp sử dụng các biến đổi sơ cấp trên dòng để tính định thức và tìm nghịch đảo (nếu có) của ma trận vuông (2 điểm).

2. Sử dụng ngôn ngữ Python để **cài đặt THỦ CÔNG** các hàm sau:

    a. Hàm cho phép đọc ma trận từ file `input.txt`: `read_file(file_name_in)` (1 điểm). Ví dụ file `input.txt`:
        
        0	1	2
        3	5	5
        5	7	5
        
    b. Hàm cho phép ghi nội định thức và ma trận nghịch đảo ra file `MSSV_output.txt` (1 điểm): `write_file(file_name_out, determinant, inverse_matrix)`. Trong đó, `MSSV` được thay thành mã số sinh viên của bạn. Ví dụ file `MSSV_output.txt`:
        
        Det: 2
        
        Inverse matrix:
        -5.0  4.5 -2.5
         5.0 -5.0  3.0
        -2.0  2.5 -1.5

    c. Hàm tính định thức của ma trận vuông sử dụng các phép biến đổi sơ cấp trên dòng: `calc_determinant_row_operation(matrix)` (3 diểm)
    
    d. Hàm tìm nghịch đảo của ma trận vuông sử dụng các phép biến đổi sơ cấp trên dòng: `invert_matrix_row_operation(matrix)`. Hàm trả về `None` nếu ma trận không khả nghịch. (3 điểm)


Bên cạnh các hàm được yêu cầu cài đặt, bạn có thể có thể cài đặt thêm một số hàm phụ trợ (nếu có).

#### Gợi ý cách tổ chức mã nguồn

In [ ]:
def read_file(file_name_in):
    '''
    Read matrix from file
    
    Inputs:
        file_name_in : str
            The name of input file
            
    Outputs:
        marix : list (of list)
            Matrix which is read from file
    '''
    
    # YOUR CODE HERE
    
    
def write_file(file_name_out, determinant, inverse_matrix):
    '''
    Write determinant and inversed matrix into file
    
    Inputs:
        file_name_out : str
            The name of output file
            
        determinant : int or float
            The determinant of matrix read from input file
        
        inversed_matrix : list (of list)
            The inverse of matrix read from input file
    '''
    
    # YOUR CODE HERE
    
    
# YOUR OTHER FUNCTIONS
    
    
def calc_determinant_row_operation(matrix):
    '''
    Calculate determinant of input matrix
    
    Inputs:
        marix : list (of list)
            Matrix which is read from file
            
    Outputs:
        determinant : int or float
            The determinant of input matrix
    '''
    
    # YOUR CODE HERE
    
    
def invert_matrix_row_operation(matrix):
    '''
    Invert a matrix
    
    Inputs:
        marix : list (of list)
            Matrix which is read from file
            
    Outputs:
        inverse_matrix : list (of list) or None
            The inverse of input matrix
            `None` when the input matrix is not invertible
    '''
    
    # YOUR CODE HERE


def main():
    matrix = read_file(file_name_in='input.txt')
    
    det = calc_determinant_row_operation(matrix)
    inv_mat = invert_matrix_row_operation(matrix)
    
    write_file(file_name_out='MSSV_output.txt', determinant=det, inverse_matrix=inv_mat)

<font style="color:red">*Lưu ý: Sinh viên **KHÔNG ĐƯỢC SỬ DỤNG** bất kỳ thư viện đại số tuyến tính nào (ví dụ `numpy.linalg`, `scipy.linalg`, `sympy.matrices`,..)* </font>

### Quy định bài nộp <a class="anchor" id="c22"></a>

* Thực hiện toàn bộ bài làm trên 1 tập tin Jupyter Notebook (.ipynb) hoặc Python (.py)


* Bạn nộp tập tin `MSSV.zip` được nén từ thư mục MSSV chứa các tập tin sau:
    1. Báo cáo toàn bộ bài làm: `MSSV.pdf`
    2. Mã nguồn: `MSSV.ipynb` hoặc `MSSV.py`


* Trong đó, nội dung tập tin báo cáo gồm có:
    - Thông tin cá nhân: họ và tên, MSSV
    - Nội dung phần tìm hiểu về phương pháp tính định thức và tìm ma trận nghịch đảo sử dụng các phép biến đổi sơ cấp trên dòng
    - Ý tưởng cài đặt hàm `calc_determinant_row_operation(matrix)` và `invert_matrix_row_operation(matrix)`
    
    
* Ví dụ minh họa cây thư mục bài nộp sau khi giải nén tập tin `MSSV.zip` như sau:
```
MSSV
├── MSSV.pdf
└── MSSV.py hoặc MSSV.ipynb
```

### Quy định chấm bài <a class="anchor" id="c23"></a>

Những trường hợp sau đây sẽ bị 0 điểm toàn bộ đồ án:
* Nộp sai quy định
* Không có báo cáo
* Thực thi mã nguồn báo lỗi

<font style="color:red">**LƯU Ý: SAO CHÉP BÀI LÀM CỦA NHAU SẼ BỊ 0 ĐIỂM TOÀN BỘ PHẦN THỰC HÀNH**</font>